version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: ./docker/Web/Dockerfile
    volumes:
      - .:/source
    depends_on:
      - postgres
  postgres:
    image: postgres:14.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  nginx:
    build:
      context: ./
      dockerfile: ./docker/Nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - web
