version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: ./docker/WebDev/Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=1
     - DOTNET_WATCH_SUPPRESS_EMOJIS=1
    volumes:
      - ./backend:/source/app
    depends_on:
      - postgres
  postgres:
    image: postgres:14.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  pgadmin4:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=example@liamg.com
      - PGADMIN_DEFAULT_PASSWORD=supersecret
    depends_on:
      - postgres
  nginx:
    build:
      context: ./
      dockerfile: ./docker/NginxDev/Dockerfile
    ports:
      - 80:80
    depends_on:
      - web
      - pgadmin4
